services:
  mysql:
    image: mysql:8.3
    container_name: mysql_projeto_php
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_php

      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: projeto_php

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro

    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
